Value = { LineOfText }- ;

KeyDivider = ":" ;

KnownKey
  = "course"
  | "programLanguage"
  | "topicTest"
  | "date"
  | "itemType"
  ;

BlockStart
  = "beginAnnonce"
  | "?begin"
  | "!begin"
  | "beginHint"
  | "beginCode"
  ;

BlockEnd
  = "endAnnonce"
  | "?end"
  | "!end"
  | "endHint"
  | "endCode"
  ;

KeyValue = KnownKey , KeyDivider , Value ;

Block = BlockStart , Value , BlockEnd , { Value } ;

ListOfStatements = { KeyValue , Block } ;

QuestionBlock = "newQuestion" , ListOfStatements ,
  "endQuestion" ;

Metadata = [ MetaCommentedLine ] , KeyValue , Block ,
  { KeyValue , MetaCommentedLine } ;

LineOfText = [ WhiteSpace ] , Word , [ WhiteSpace ] ,
  [ Newline ] , { Word | WhiteSpace } ;

WhiteSpace = { "\t" | " " }- ;

MetaCommentedLine
  = "---"
  | "##"
  | "///" , { WhiteSpace } , [ LineOfText ]
  ;

Word = { Character }- ;

Symbol
  = "[" | "]" | "{" | "}" | "(" | ")" | "<"
  | ">" | "'" | '"' | "=" | "|" | "." | ","
  | ";"
  ;

Character = Letters | Digit | Symbol | "_" | " " ;

Digit
  = "0" | "1" | "2" | "3" | "4" | "5" | "6"
  | "7" | "8" | "9"
  ;

Tab = "\t" ;

Space = " " ;

Newline = "\n" | "\r" | "\r\n" | "\n\r" ;

Letters = Latin | Cyrylic ;

Latin
  = "A" | "B" | "C" | "D" | "E" | "F" | "G"
  | "H" | "I" | "J" | "K" | "L" | "M" | "N"
  | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
  | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
  | "c" | "d" | "e" | "f" | "g" | "h" | "i"
  | "j" | "k" | "l" | "m" | "n" | "o" | "p"
  | "q" | "r" | "s" | "t" | "u" | "v" | "w"
  | "x" | "y" | "z"
  ;

Cyrylic
  = "А" | "Б" | "В" | "Г" | "Ґ" | "Д" | "Е"
  | "Є" | "Ж" | "З" | "И" | "І" | "Ї" | "Й"
  | "К" | "Л" | "М" | "Н" | "О" | "П" | "Р"
  | "С" | "Т" | "У" | "Ф" | "Х" | "Ц" | "Ч"
  | "Ш" | "Щ" | "Ь" | "Ю" | "Я" | "а" | "б"
  | "в" | "г" | "ґ" | "д" | "е" | "є" | "ж"
  | "з" | "и" | "і" | "ї" | "й" | "к" | "л"
  | "м" | "н" | "о" | "п" | "р" | "с" | "т"
  | "у" | "ф" | "х" | "ц" | "ч" | "ш" | "щ"
  | "ь" | "ю" | "я"
  ;