@startuml Usecases
scale 3
actor User as U
title Сценарій використання: публікація
box "Розроблена система" #White
participant CLIClient as CLI

participant GoogleWorkspaceService as GWS
database Артефакти as State
end box
participant GoogleAPI as GAPI

U -> CLI : публікація тестів
activate CLI

CLI -> GWS: конфігурація вибірки питань
activate GWS
State <- GWS: отриманя списку питань
GWS -> GAPI: створення/оновлення форми
GWS -> GAPI: створенння/оноовлення питань
GWS -> CLI: успішно збережено
CLI -> U: компіляція завершена
deactivate GWS

@enduml